capstone/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from capstone import db
from capstone.forms import UserCreateForm, UserLoginForm
from capstone.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(userid=form.userid.data).first()
        email = User.query.filter_by(email=form.email.data).first()
        if not user and not email:
            user = User(userid=form.userid.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data,
                        username=form.username.data,
                        authority=1)
                        #authority=form.authority.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        elif user:
            flash('이미 존재하는 사용자입니다.')
        elif email:
            flash('이미 사용중인 이메일입니다.')
    return render_template('auth/signup.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(userid=form.userid.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

capstone/views/process_views.py
from datetime import datetime
import io

from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.utils import redirect
import requests
import pytz
import base64

from capstone import db
from capstone.forms import ImageForm
from capstone.models import User
from capstone.models import Image
from capstone.models import Report

bp = Blueprint('process', __name__, url_prefix='/process')

def is_image_url(url):
    ext = url.split('.')[-1].lower()

    headers = requests.head(url).headers
    content_type = headers.get('Content-Type').lower() if 'Content-Type' in headers else ''

    if 'image' in content_type or ext in ['jpg', 'jpeg', 'png', 'gif']:
        return True
    else:
        return False

def request_process(id):
    data = {'value': id}
    url = 'https://pcbdd.ngrok.app/process'
    response = requests.post(url, json=data)

    if response.status_code == 200:
        return response.json()['result']
    else:
        return None

@bp.route('/img', methods=('GET', 'POST'))
def img():
    form = ImageForm()
    if request.method == 'POST':
        if request.form['type'] == '저장':
            file = request.files['image-file']
            typ = int(request.form['PCB_type'])
            url = request.form['image-url']

            if file:
                user_id = session.get('user_id')
                time_now = datetime.now(pytz.timezone('Asia/Seoul'))
                image = Image(user=user_id, image=file.read(), type=typ, date=time_now)
                db.session.add(image)
                db.session.commit()

                flash("파일이 업로드되었습니다.")
                return render_template('process/img.html', form=form)
            elif len(url) != 0:
                if is_image_url(url):
                    response = requests.get(url)
                    if response.status_code == 200:
                        user_id = session.get('user_id')
                        time_now = datetime.now(pytz.timezone('Asia/Seoul'))
                        image = Image(user=user_id, image=response.content, type=typ, date=time_now)
                        db.session.add(image)
                        db.session.commit()

                        flash("파일이 업로드되었습니다.")
                        return render_template('process/img.html', form=form)
                    else:
                        flash("오류가 발생했습니다.")
                else:
                    flash("올바른 url을 입력해주세요.")
            else:
                flash("파일을 업로드해주세요.")
    return render_template('process/img.html', form=form)

@bp.route('/cam', methods=('GET', 'POST'))
def cam():
    if request.method == 'POST':
        if request.form.get('source') == 'javascript':
            user_id = session.get('user_id')
            typ = int(request.form.get('type'))
            time_now = datetime.now(pytz.timezone('Asia/Seoul'))
            data_url = request.form['image']
            data = base64.b64decode(data_url.split(',')[1])
            image = Image(user=user_id, image=data, type=typ, date=time_now)
            db.session.add(image)
            db.session.commit()

    return render_template('process/cam.html')

@bp.route('/result/<id>', methods=('GET', 'POST'))
def result(id):
    id = request_process(id)  # 머신러닝 서버

    if id is None:
        return render_template('404.html')

    image = Image.query.filter_by(id=id).first()
    image.result = base64.b64encode(image.result).decode('utf-8')

    return render_template('process/result.html', image=image)

@bp.route('/captured', methods=('GET', 'POST'))
def captured():
    if request.method == 'POST':
        if request.form.get('source') == 'javascript':
            image_id = request.form.get('id')
            image = Image.query.get(image_id)
            if image:
                db.session.delete(image)
                db.session.commit()
                return {'success': True}
    else:
        user_id = session.get('user_id')
        images = Image.query.filter_by(user=user_id).all()
        for image in images:
            image.image = base64.b64encode(image.image).decode('utf-8')
        return render_template('process/captured.html', images=images)

@bp.route('/error_report/<id>', methods=('GET', 'POST'))
def error(id):
    if request.method == 'POST':
        if request.form.get('source') == 'javascript':
            user = session.get('user_id')
            content = request.form.get('content')

            if content:
                report = Report(user=user, image=id, content=content)
                db.session.add(report)
                db.session.commit()
    else:
        return render_template('process/error.html', id=id)

@bp.route('/report', methods=('GET', 'POST'))
def report():
    reports = Report.query.all()
    return render_template('process/report.html', reports=reports)

capstone/templates/process/cam.html
<!DOCTYPE html>
<html lang="ko">
<meta charset="UTF-8">

<head>
	<link href="style.css" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
	<title> PCB 결함 탐지 </title>

	<script>
		var video = null;
		var canvas1 = null;
        var canvas2 = null;
		var ctx1 = null;
        var ctx2 = null;
		var interval = 0;

		function startVideo() {
			video = document.getElementById("video");
			canvas1 = document.getElementById("canvas1");
			canvas2 = document.getElementById("canvas2");
			ctx1 = canvas1.getContext("2d");
			ctx2 = canvas2.getContext("2d");

			if (navigator.mediaDevices.getUserMedia) {
				navigator.mediaDevices.getUserMedia({ video: true })
					.then(function (stream) {
						video.srcObject = stream;
						video.onloadedmetadata = function (e) {
							video.play();
						};

						document.getElementById('capture').disabled = false;
						document.getElementById('auto_apply').disabled = false;
						document.getElementById('auto_disapply').disabled = false;
					})
					.catch(function (err) {
						console.log("An error occurred: " + err);
					});
			}
		}

		function stopVideo() {
			if (video) {
				video.pause();
				video.srcObject = null;

				document.getElementById('capture').disabled = true;
				document.getElementById('save').disabled = true;
                document.getElementById('auto_apply').disabled = true;
                document.getElementById('auto_disapply').disabled = true;
			}

			if (ctx1) {
				ctx1.clearRect(0, 0, canvas1.width, canvas1.height);
				ctx2.clearRect(0, 0, canvas2.width, canvas2.height);
			}
		}

		function takeSnapshot() {
			ctx1.drawImage(video, 0, 0, canvas1.width, canvas1.height);
			ctx2.drawImage(video, 0, 0, canvas2.width, canvas2.height);

			document.getElementById('analyze-button').disabled = false;
			document.getElementById('save').disabled = false;
            saveImage()
		}

		function saveImage() {
			var formData = new FormData();
            var type = document.getElementById("PCB_type");
			formData.append('source', 'javascript');
			formData.append('image', canvas2.toDataURL());
            formData.append('type', type.options[type.selectedIndex].value);

			var xhr = new XMLHttpRequest();
			xhr.open('POST', '{{ url_for('process.cam') }}');
			xhr.onload = function () {
				if (xhr.status === 200) {
					console.log('Image uploaded successfully.');
				} else {
					console.log('Failed to upload image.');
				}
			};
			xhr.send(formData);
		}

		function downloadCanvas() {
			var canvas2 = document.getElementById("canvas2");
			var image = canvas2.toDataURL("image/png").replace("image/png", "image/octet-stream");
			var link = document.createElement('a');

			link.download = "image.png";
			link.href = image;
			link.click();
		}

		function takeAuto() {
			takeSnapshot()
			clearInterval(interval)
			interval = setInterval(function () {
				takeSnapshot()
			}, document.getElementById('myInterval').value);

		}

		function stopAuto() {
			clearInterval(interval)
			interval = 0
		}

        function capturedPopup() {
            window.open("{{ url_for('process.captured') }}", "captured", "width=600, height=1000, left=0, top=0");
		}

        function VideoHandler(self) {
            var target = document.querySelector('body');
            if (self.value == 'off') {
                self.value = 'on'
                startVideo();
            }
            else {
                self.value = 'off'
                stopVideo();
            }
        }
	</script>
</head>

<body>
	{% if g.user %}
	<div class="outline">
		<a class="title" href="/"> 컴퓨터 비전 기반 PCB 결함 탐지 </a>
		<div class="inline">
			<p class="margin1 link-box">
				<a href="https://youtu.be/U6IT4eSH8gA" class="blue-link" target="_blank">
					실제 예제 보기
				</a>
				|
				<a href="https://github.com/choguitar/capstone" class="blue-link" target="_blank">
					GitHub에서 보기
				</a>
			</p>

			<p class="tab_menu">
				<a class="mode_btn" href="{{ url_for('process.img') }}"><button type="img_btn " class="mini-button"> 이미지 첨부 </button></a>
				<a class="mode_btn" href="{{ url_for('process.cam') }}"><button type="cam_btn" class="mini-button" style="margin-right:1px"
						disabled> 웹캠 연동 </button></a>
			</p>

			<form method="post" enctype="multipart/form-data">
				<input type="hidden" name="recap" id="recap_response">
				<div class="option-box first">
					<div>
                        <div style="width:25%; height:60px; margin:auto;" >
                            <p style="vertical-align:center; float:left; font-size:15px; padding-right:10px">비디오 활성화</p>
                            <div class="wrapper" style="margin:auto; padding: 9px; text-align:center;">
                                <input type="checkbox" id="switch" value="off" onclick="VideoHandler(this);">
                                <label for="switch" class="switch_label">
                                    <span class="onf_btn"></span>
                                </label>
                            </div>
                        </div>

                        <select name="PCB_type" id="PCB_type" style="margin-bottom:20px; height:50px; border: 5px solid #7dc9e2; border-radius: 0.3em;">
                            <option value="0"> TM_Chassis_Single </option>
                            <option value="1"> TM_Chassis_MULT </option>
                            <option value="2"> TM-A_Chassis_Single </option>
                            <option value="3"> TM-A_Chassis_MULT </option>
                        </select>
                        <br>

						<input type=button id="capture" value="캡쳐" class="mini-button" onclick="{takeSnapshot()}" style="margin-bottom:5px;"
							disabled>
						<input type=button id="save" value="저장" class="mini-button" onclick="{downloadCanvas()}" style="margin-bottom:5px;"
							disabled>
						<br>
						<input type=number id="myInterval" value="300" style="width: 60px; margin-top: 20px;"> msec 마다 자동 캡쳐
						<input type=button id="auto_apply" value="적용" onclick="{takeAuto()}" disabled>
						<input type=button id="auto_disapply" value="비활성화" onclick="{stopAuto()}" disabled>
					</div>

					<br>
					<input type=button id="analyze-button" type="analyze" class="submit" style="margin:auto" value="조회"
						onclick="capturedPopup()">
                    <input type="hidden" name="source" value="form">
				</div>
			</form>

			<video id="video" width="640" height="360"></video><br>
			<canvas id="canvas1" width="480" height="270"></canvas><br>
			<canvas id="canvas2" width="4032" height="2268" style="display: none"></canvas>
		</div>
	</div>
	<p> <a href="{{ url_for('auth.logout') }}"> {{ g.user.username }} (로그아웃) </a> </p>
	{% else %}
	<p> <a href="{{ url_for('auth.login') }}"> 로그인 </a> </p>
	{% endif %}
	<div style="margin-top: 10%; font-size: 10px">2023년 1학기 세종대학교 캡스톤 5조 팀 프로젝트</div>
</body>

</html>

capstone/templates/process/captured.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <title> 저장된 이미지 조회 </title>

  <script>
    function resultPopup(id) {
      url = '/process/result/' + id.toString();
      window.open(url, "result", "width=1010, height=630, left=400, top=200");
    }
    function deleteImage(imageId) {
      var formData = new FormData();
      formData.append('source', 'javascript');
      formData.append('id', imageId);

      var xhr = new XMLHttpRequest();
      xhr.open('POST', '{{ url_for('process.captured') }}');
      xhr.onload = function () {
        if (xhr.status === 200) {
          var response = JSON.parse(xhr.responseText);
          console.log(response);
          if (response.success) {
            location.reload(); // Reload the page after successful deletion
          } else {
            console.log(response.message); // Log the error message if deletion failed
          }
        } else {
          console.log('Failed to send request.');
        }
      };
      xhr.send(formData);
    }
  </script>
</head>

<body style="margin:auto; max-width:550px; padding:20px;">
  <table style="width:100%; border: solid 8px #0ca3d2; border-radius: 0.5em 0.5em 0.5em 0.5em;">
    <thead style="background-color:#f3f3f3; border: solid #555; border-bottom: solid 2px; height:40px;">
      <tr>
        <th style="text-align:center; width:10em; margin:auto">이미지</th>
        <th style="text-align:center; width:10em; margin:auto">날짜</th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      {% for image in images %}
      <tr>
        <td style="width:106px; margin:auto; text-align:center"><img src="data:image/png;base64,{{ image.image }}"
            alt="{{ image.id }}" width="100" height="100"></td>
        <td style="text-aling:center">{{ image.date }}</td>
        <td style="margin:auto; text-align:center; padding:10px;">
          <form method="post">
            <input type="button" id="analyze-button" type="analyze" class="button" style="margin:auto" value="분석"
              onclick="resultPopup({{ image.id }})">
            <input type="button" id="delete-button" type="delete" class="button" style="margin:auto" value="삭제"
              onclick="deleteImage({{ image.id }})">
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</body>

</html>

capstone/templates/process/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> 오류 신고 </title>

    <style>
        .submit {
            margin: 1%;
            padding: 1% 5%;
            width: 30%;
            height: 50px;
            font-size: 18px;
            font-weight: bold;
            color: #404040;
            background: #85bdea;
            border: 1px solid;
            border-color: #c4c4c4 #d1d1d1 #d4d4d4;
            border-radius: 2px 2px 2px 2px;
            outline: 5px solid #eff4f7;
            -moz-outline-radius: 3px;
            -webkit-box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.12);
            box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.12);
        }
        .submit:hover {
            background-color: #a2d5f5;
            outline-color: #dedede;
        }
    </style>

    <script>
        function closePopup(id) {
			var formData = new FormData();
            var content = document.getElementById('content').value;
			formData.append('source', 'javascript');
			formData.append('content', content);

			var xhr = new XMLHttpRequest();
			xhr.open('POST', '{{ url_for('process.error', id=id) }}');
			xhr.onload = function () {
				if (xhr.status === 200) {
					console.log('Image uploaded successfully.');
				} else {
					console.log('Failed to upload image.');
				}
			};
			xhr.send(formData);

            window.close();
		}
    </script>
</head>
<body>
    <div style="text-align: center">
        <p> 아래에 오류 사항을 적어주십시오. </p>
        <form>
            <textarea name="content" id="content" style="width: 100%; height: 100%" rows="25"></textarea>
            <br>
            <input type="submit" value="제출" class="submit" onclick="closePopup({{ id }})">
        </form>
    </div>
</body>
</html>

capstone/templates/process/img.html
{%with messages = get_flashed_messages()%}
{%if messages %}
<script type="text/javascript">
	alert("{{messages[-1]}}");
</script>
{%endif%}
{%endwith%}

<!DOCTYPE html>
<html lang="ko">
<meta charset="UTF-8">

<head>
	<link href="style.css" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
	<title> PCB 결함 탐지 </title>
	
	<script>
        var isLoad = false;

		function showImage(event) {
			var imageFile = event.target.files[0];
			var imageObjectURL = URL.createObjectURL(imageFile);
			document.getElementById('image').src = imageObjectURL;
			document.getElementById('image').style.display = "block";
			document.getElementById('delete-button').style.display = "block";
            isLoad = true;
		}

		function loadImage() {
			var url = document.getElementById('image-url').value;
			document.getElementById('image').src = url;
			document.getElementById('image').style.display = "block";
			document.getElementById('delete-button').style.display = "block";
            isLoad = true;
		}

		function capturedPopup() {
            window.open("{{ url_for('process.captured') }}", "captured", "width=600, height=1000, left=0, top=0");
		}
	</script>
</head>

<body>
	{% if g.user %}
	<div class="outline">
		<a class="title" href="/"> 컴퓨터 비전 기반 PCB 결함 탐지 </a>
		<div class="inline">
			<p class="margin1 link-box">
				<a href="https://youtu.be/U6IT4eSH8gA" class="blue-link" target="_blank">
					실제 예제 보기
				</a>
				|
				<a href="https://github.com/choguitar/capstone" class="blue-link" target="_blank">
					GitHub에서 보기
				</a>
			</p>

			<p class="tab_menu">
				<a class="mode_btn" href="{{ url_for('process.img') }}"><button type="img_btn" class="mini-button" disabled> 이미지 첨부
					</button></a>
				<a class="mode_btn" href="{{ url_for('process.cam') }}"><button type="cam_btn" class="mini-button"> 웹캠 연동 </button></a>
			</p>
			<form method="post" enctype="multipart/form-data">
				<div class="option-box first">
					<div class="option-right">
						<input type="url" id="image-url" name="image-url" placeholder="URL 입력" style="height:40px;">
                        <input type="button" onclick="loadImage()" class="option-left" name="type" value="링크 사진 불러오기" style="height:70px; margin-top:20px;">
                        <div class="option-left">
							<label for="image-file" name="image-file" accept="image/*" onchange="showImage(event)"
								style="width:200px">
								내 PC에서 가져오기
							</label>
						</div>
						<div class="option-right-small" style="display: none">
							또는 파일 업로드:
							<input type="file" id="image-file" name="image-file" accept="image/*"
								onchange="showImage(event)">
						</div>
					</div>

                    <br>
                    <select name="PCB_type" id="PCB_type"
                    style="margin-top:20px; height:50px; border: 5px solid #7dc9e2; border-radius: 0.3em;">
                        <option value="0"> TM_Chassis_Single </option>
                        <option value="1"> TM_Chassis_MULT </option>
                        <option value="2"> TM-A_Chassis_Single </option>
                        <option value="3"> TM-A_Chassis_MULT </option>
                    </select>

					<img id="image" style="display: none; margin: auto;" width="500" height="auto" src="" alt="">

					<p id="error-message" style="display: none; color: red;">Error loading image.</p>
				</div>

				<input type="submit" id="analyze-button" name="type" class="split-submit" value="저장"
					style="margin-bottom:20px; margin-right:10px;">
				<input type="submit" id="check-button" name="type" class="split-submit" value="조회"
					style="margin-bottom:20px" onclick="capturedPopup()">
			</form>

			<div
				style="background-color: rgb(255, 255, 255); border: 1px solid rgb(204, 204, 204); box-shadow: rgba(0, 0, 0, 0.2) 2px 2px 3px; position: absolute; transition: visibility 0s linear 0.3s, opacity 0.3s linear 0s; opacity: 0; visibility: hidden; z-index: 2000000000; left: 0px; top: -10000px;">
				<div
					style="width: 100%; height: 100%; position: fixed; top: 0px; left: 0px; z-index: 2000000000; background-color: rgb(255, 255, 255); opacity: 0.05;">
				</div>
				<div class="g-recaptcha-bubble-arrow"
					style="border: 11px solid transparent; width: 0px; height: 0px; position: absolute; pointer-events: none; margin-top: -11px; z-index: 2000000000;">
				</div>
				<div class="g-recaptcha-bubble-arrow"
					style="border: 10px solid transparent; width: 0px; height: 0px; position: absolute; pointer-events: none; margin-top: -10px; z-index: 2000000000;">
				</div>
				<div style="z-index: 2000000000; position: relative;"><iframe
						title="recaptcha challenge expires in two minutes" src="./waifu2x_files/bframe.html"
						name="c-c5lcwcub9i78" frameborder="0" scrolling="no"
						sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox"
						style="width: 100%; height: 100%;"></iframe></div>
			</div>

			<div
				style="background-color: rgb(255, 255, 255); border: 1px solid rgb(204, 204, 204); box-shadow: rgba(0, 0, 0, 0.2) 2px 2px 3px; position: absolute; transition: visibility 0s linear 0.3s, opacity 0.3s linear 0s; opacity: 0; visibility: hidden; z-index: 2000000000; left: 0px; top: -10000px;">
				<div
					style="width: 100%; height: 100%; position: fixed; top: 0px; left: 0px; z-index: 2000000000; background-color: rgb(255, 255, 255); opacity: 0.05;">
				</div>
				<div class="g-recaptcha-bubble-arrow"
					style="border: 11px solid transparent; width: 0px; height: 0px; position: absolute; pointer-events: none; margin-top: -11px; z-index: 2000000000;">
				</div>
				<div class="g-recaptcha-bubble-arrow"
					style="border: 10px solid transparent; width: 0px; height: 0px; position: absolute; pointer-events: none; margin-top: -10px; z-index: 2000000000;">
				</div>
				<div style="z-index: 2000000000; position: relative;"><iframe
						title="recaptcha challenge expires in two minutes" src="./waifu2x_files/bframe.html"
						name="c-c5lcwcub9i78" frameborder="0" scrolling="no"
						sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox"
						style="width: 100%; height: 100%;"></iframe></div>
			</div>
		</div>
	</div>
	<p> <a href="{{ url_for('auth.logout') }}"> {{ g.user.username }} (로그아웃) </a> </p>
	{% else %}
	<p> <a href="{{ url_for('auth.login') }}"> 로그인 </a> </p>
	{% endif %}
	<div style="margin-top: 10%; font-size: 10px">2023년 1학기 세종대학교 캡스톤 5조 팀 프로젝트</div>
</body>

</html>

capstone/templates/process/report.html
<!DOCTYPE html>
<html lang="ko">
<meta charset="UTF-8">

<head>
	<link href="style.css" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
	<title> 오류 보고 </title>
</head>

<body style="margin:auto; max-width:550px; padding:20px;">
    {% if g.user %}
    <table style="width:100%; border: solid 8px #0ca3d2; border-radius: 0.5em 0.5em 0.5em 0.5em;">
        <thead style="background-color:#f3f3f3; border: solid #555; border-bottom: solid 2px; height:40px;">
            <tr>
                <th style="text-align:center; width:10em; margin:auto"> 이미지 번호</th>
                <th style="text-align:center; width:10em; margin:auto"> 사용자 </th>
                <th style="text-align:center; width:10em; margin:auto"> 내용 </th>
            </tr>
        </thead>
        <tbody>
        {% for report in reports %}
        <tr>
            <td style="width:106px; margin:auto; text-align:center"> {{ report.image }} </td>
            <td style="text-aling:center"> {{ report.user }} </td>
            <td style="text-aling:center"> {{ report.content }} </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <p> <a href="{{ url_for('auth.logout') }}"> {{ g.user.username }} (로그아웃) </a> </p>
	{% else %}
	<p> <a href="{{ url_for('auth.login') }}"> 로그인 </a> </p>
	{% endif %}
	<div style="margin-top: 10%; font-size: 10px">2023년 1학기 세종대학교 캡스톤 5조 팀 프로젝트</div>
</body>

</html>

capstone/templates/process/result.html
{%with messages = get_flashed_messages()%}
{%if messages %}
<script type="text/javascript">
	alert("{{messages[-1]}}");
</script>
{%endif%}
{%endwith%}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>분석 결과</title>

    <style>
        .error_report_btn {
            margin: 1%;
            padding: 1% 5%;
            width: 30%;
            height: 50px;
            font-size: 18px;
            font-weight: bold;
            color: #ffffff;
            background: #e0557d;
            border: 1px solid;
            border-color: #c4c4c4 #d1d1d1 #d4d4d4;
            border-radius: 2px 2px 2px 2px;
            outline: 5px solid #eff4f7;
            -moz-outline-radius: 3px;
            -webkit-box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.12);
            box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.12);
        }

        .error_report_btn:hover {
            background-color: #CF4E73;
            outline-color: #dedede;
        }

        .error_report_btn:active {
            background-color: #ED5A84;
        }
    </style>

    <script>
        function errorPopup(id) {
            url = '/process/error_report/' + id.toString();
            window.open(url, "error", "width=600, height=480, left=0, top=0");
		}
    </script>
</head>
<body>
    <div style="text-align: center">
        <img src="data:image/png;base64,{{ image.result }}" alt="image" width="1000" height="550">
        <br>
        <button name="err_report" id="err_report" class="error_report_btn" onclick="errorPopup({{ image.id }})"> 오류 신고 </button>
    </div>
</body>
</html>