capstone/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from capstone import db
from capstone.forms import UserCreateForm, UserLoginForm
from capstone.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(userid=form.userid.data).first()
        email = User.query.filter_by(email=form.email.data).first()
        if not user and not email:
            user = User(userid=form.userid.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data,
                        username=form.username.data,
                        authority=1)
                        #authority=form.authority.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        elif user:
            flash('이미 존재하는 사용자입니다.')
        elif email:
            flash('이미 사용중인 이메일입니다.')
    return render_template('auth/signup.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(userid=form.userid.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

capstone/views/main_views.py
from flask import Blueprint, url_for, session, render_template, current_app
from werkzeug.utils import redirect

from capstone import db
from capstone.models import User

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/select', methods=('GET', 'POST'))
def select():
    return render_template('main.html')

@bp.route('/')
def index():
    user_id = session.get('user_id')
    if user_id is None:
        return redirect(url_for('auth.login'))
    elif user_id == 1:
        return redirect(url_for('process.report'))
    else:
        return redirect(url_for('main.select'))

capstone/views/process_views.py
from datetime import datetime
import io

from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.utils import redirect
import requests
import pytz
import base64

from capstone import db
from capstone.forms import ImageForm
from capstone.models import User
from capstone.models import Image
from capstone.models import Report

bp = Blueprint('process', __name__, url_prefix='/process')

def is_image_url(url):
    ext = url.split('.')[-1].lower()

    headers = requests.head(url).headers
    content_type = headers.get('Content-Type').lower() if 'Content-Type' in headers else ''

    if 'image' in content_type or ext in ['jpg', 'jpeg', 'png', 'gif']:
        return True
    else:
        return False

def request_process(id):
    data = {'value': id}
    url = 'https://pcbdd.ngrok.app/process'
    response = requests.post(url, json=data)

    if response.status_code == 200:
        return response.json()['result']
    else:
        return None

@bp.route('/img', methods=('GET', 'POST'))
def img():
    form = ImageForm()
    if request.method == 'POST':
        if request.form['type'] == '저장':
            file = request.files['image-file']
            typ = int(request.form['PCB_type'])
            url = request.form['image-url']

            if file:
                user_id = session.get('user_id')
                time_now = datetime.now(pytz.timezone('Asia/Seoul'))
                image = Image(user=user_id, image=file.read(), type=typ, date=time_now)
                db.session.add(image)
                db.session.commit()

                flash("파일이 업로드되었습니다.")
                return render_template('process/img.html', form=form)
            elif len(url) != 0:
                if is_image_url(url):
                    response = requests.get(url)
                    if response.status_code == 200:
                        user_id = session.get('user_id')
                        time_now = datetime.now(pytz.timezone('Asia/Seoul'))
                        image = Image(user=user_id, image=response.content, type=typ, date=time_now)
                        db.session.add(image)
                        db.session.commit()

                        flash("파일이 업로드되었습니다.")
                        return render_template('process/img.html', form=form)
                    else:
                        flash("오류가 발생했습니다.")
                else:
                    flash("올바른 url을 입력해주세요.")
            else:
                flash("파일을 업로드해주세요.")
    return render_template('process/img.html', form=form)

@bp.route('/cam', methods=('GET', 'POST'))
def cam():
    if request.method == 'POST':
        if request.form.get('source') == 'javascript':
            user_id = session.get('user_id')
            typ = int(request.form.get('type'))
            time_now = datetime.now(pytz.timezone('Asia/Seoul'))
            data_url = request.form['image']
            data = base64.b64decode(data_url.split(',')[1])
            image = Image(user=user_id, image=data, type=typ, date=time_now)
            db.session.add(image)
            db.session.commit()

    return render_template('process/cam.html')

@bp.route('/result/<id>', methods=('GET', 'POST'))
def result(id):
    id = request_process(id)  # 머신러닝 서버

    if id is None:
        return render_template('404.html')

    image = Image.query.filter_by(id=id).first()
    image.result = base64.b64encode(image.result).decode('utf-8')

    return render_template('process/result.html', image=image)

@bp.route('/captured', methods=('GET', 'POST'))
def captured():
    if request.method == 'POST':
        if request.form.get('source') == 'javascript':
            image_id = request.form.get('id')
            image = Image.query.get(image_id)
            if image:
                db.session.delete(image)
                db.session.commit()
                return {'success': True}
    else:
        user_id = session.get('user_id')
        images = Image.query.filter_by(user=user_id).all()
        for image in images:
            image.image = base64.b64encode(image.image).decode('utf-8')
        return render_template('process/captured.html', images=images)

@bp.route('/error_report/<id>', methods=('GET', 'POST'))
def error(id):
    if request.method == 'POST':
        if request.form.get('source') == 'javascript':
            user = session.get('user_id')
            content = request.form.get('content')

            if content:
                report = Report(user=user, image=id, content=content)
                db.session.add(report)
                db.session.commit()
    else:
        return render_template('process/error.html', id=id)

@bp.route('/report', methods=('GET', 'POST'))
def report():
    reports = Report.query.all()
    return render_template('process/report.html', reports=reports)

capstone/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- capstone CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
</body>
</html>

capstone/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

capstone/templates/main.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title> PCB 결함 탐지 </title>
</head>

<body>
    {% if g.user %}
    <div class="outline">
        <h1 class="title"> 컴퓨터 비전 기반 PCB 결함 탐지 </h1>
        <div class="inline">
            <p class="margin1 link-box">
                <a href="https://youtu.be/U6IT4eSH8gA" class="blue-link" target="_blank">
                    실제 예제 보기
                </a>
                |
                <a href="https://github.com/choguitar/capstone" class="blue-link" target="_blank">
                    GitHub에서 보기
                </a>
            </p>

            <p class="tab_menu">
				<a class="mode_btn" href="{{ url_for('process.img') }}"><button type="img_btn" class="mini-button"> 이미지 첨부 </button></a>
				<a class="mode_btn" href="{{ url_for('process.cam') }}"><button type="cam_btn" class="mini-button"> 웹캠 연동 </button></a>
			</p>
        </div>
    </div>
    <p> <a href="{{ url_for('auth.logout') }}"> {{ g.user.username }} (로그아웃) </a> </p>
    {% else %}
        <p> <a href="{{ url_for('auth.login') }}"> 로그인 </a> </p>
    {% endif %}
    <div style="margin-top: 10%; font-size: 10px">2023년 1학기 세종대학교 캡스톤 5조 팀 프로젝트</div>
</body>

</html>

capstone/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if g.user %}
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>